config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end

  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  def age_in_days
    (DateTime.now.to_date - created_at.to_date).to_i
  end

  def days_left
    7-(age_in_days)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
     before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected

   def after_sign_in_path_for(resource)
     user_path(resource)
   end
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:notice] = "Your item was saved!"
    else
      flash[:error] = "There was a problem saving your item!"
    end
    redirect_to user_path(current_user)
  end

  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html
      format.js
    end
  end

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @item = Item.new
    @items = current_user.items
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
 <form>
  <%= form_for [current_user, item] do |f| %>
   <% if item.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(item.errors.count, "error") %>.</h4>
       <ul>
         <% item.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
  
  <div class="form-group">
    <h4><%= f.label :name, "Add a New To-Do!" %></h4>
    <%= f.text_field :name, class: 'form-control item', placeholder: "Enter your item here" %>
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
 <% end %>
</form>

app/views/items/_item.html.erb
<tr id="item-<%= item.id %>">
  <td><%= link_to "", user_item_path(current_user, item), method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %><%= item.name %></td>
  <td><%= item.days_left %></td>
</tr>

app/views/items/destroy.js.erb
 <% if @item.destroyed? %>
  $("#item-<%= @item.id %>").fadeOut(1300);
 <% else %>
  $("#item-<%= @item.id %>").prepend("<div class='alert alert-danger'><%= flash[:error] = "Your comment couldn't be deleted. Please try again." %></div>");
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff-RC</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
   <ul class="nav nav-tabs">
        <li><%= link_to "Home", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><% if current_user %><%= link_to "To-Do's", user_path(current_user) %><% end %></li>
   
         <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.name || current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
         
        </ul> 

        <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

<%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<h1 class="center">My Checklist</h1>

<h3 class="center"><i>Welcome, <%= ( current_user.name ? current_user.name : current_user.email ) %> - let's get things done!</i></h3>  

<div style='margin-top: 15px;'>
  <%= render partial: 'items/form', locals: { item: @item } %>
</div>

<table class="table table-hover">
  <tr>
    <th>Item</th>
    <th>Days Left</th>
   </tr> 
  <%= render @items %>
</table>

   

app/views/welcome/about.html.erb
<div class="jumbotron pink">
  <h2>About Blocitoff-RC</h2>
  <h5><em>Created by Rachel Colby</em></h5>
  <h4>Blocitoff-RC was inspired by the oft-quoted adage, <em>"If you haven't done it by now, it must not be that important!"</em> </h4>
  <h4>It's easy to add and add to your to-do list, and it's just as easy to get overwhelemed and distracted by the sheer quantity of to-do's as the list keeps growing and growing. Blocitoff-RC was created to help busy professionals let go of low-priority to-do's that need to drop off the list and focus on the things that matter.</h4>
  <h4>At Blocitoff-RC, we're committed to helping you eliminate those old to-do's you know you'll never get to. </h4>
  <h3><em><strong>So check it off, or we'll blocitoff!</strong></em></h3>
</div>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron pink">
  <h1>Blocitoff</h1>

  <h3>Welcome to Blocitoff-RC, the premier to-do list management app!</h3>
    <p>Do you find yourself adding to your to-do list more than crossing things off? Do you get distracted and overwhelmed by old to-do's that just don't go away? </p>
    <p>Ever been told, <strong>"If you haven't done it by now, it must not be that important?"<strong> </p>
    <p>At Blocitoff-RC, we're committed to helping you eliminate those old to-do's you know you'll never get to. We say:
  <h3><strong>Check it off, or we'll blocitoff! </em></strong></h3>
  </br>
      <p>
          <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
      </p>
      <p><strong>Join the movement!</strong><br>You'll quickly see your to-do list tamed and your productivity skyrocket.</p>
</div>